Language = {
    open = "Ouvrir le sac de vêtements",
    pickup = "Ramasser le sac de vêtements",
    placing = "Placement du sac de vêtements...",
    picking = "Ramassage du sac de vêtements...",
    noitem = "Vous n'avez pas de sac de vêtements.",
    nooutfit = "Vous n'avez aucune tenue dans le sac.",
    wearing = "Vous êtes en train d'enfiler la tenue...",
    maxoutfits = "Vous avez enregistré le nombre maximum de tenues.",
    save = "Enregistrer",
    savedoutfit = "Tenue enregistrée sous :",
    saveoutfit = "Enregistrer la tenue",
    savenowoutfit = "Enregistrer la tenue actuelle",
    outfitname = "Nom de la tenue",
    myoutfit = "Ma Tenue",
    outfiton = "La tenue est maintenant portée",
    nooutfits = "Vous n'avez aucune tenue enregistrée.",
    moreoptions = "Cliquez pour plus d'options",
    outfits = "Tenues",
    showsavedoutfits = "Afficher les tenues enregistrées",
    dressup = "S'habiller",
    rename = "Renommer",
    renameoutfit = "Renommer la tenue",
    renameoutfitname = "Nouveau nom de tenue",
    delete = "Supprimer",
    title = "Sac de Tenues",
    placeditem = "Vous avez placé le sac de vêtements avec succès.",
}


--[[ Czech Language
Language = {
    open = "Otevřít tašku s oblečením",
    pickup = "Vzít tašku s oblečením",
    placing = "Pokládání tašky s oblečením...",
    picking = "Braní tašky s oblečením...",
    noitem = "Nemáš u sebe tašku s oblečením.",
    nooutfit = "Nemáš žádný outfit v tašce.",
    wearing = "Momentálně si oblékáš outfit...",
    maxoutfits = "Máš uložený maximální počet outfitů.",
    save = "Uložit",
    savedoutfit = "Outfit uložen jako:",
    saveoutfit = "Uložit outfit",
    savenowoutfit = "Uloží aktuální outfit",
    outfitname = "Název outfitu",
    myoutfit = "Můj Outfit",
    outfiton = "Outfit je nyní na tobě",
    nooutfits = "Nemáš žádný outfit uložený.",
    moreoptions = "Klikni pro více možností",
    outfits = "Outfity",
    showsavedoutfits = "Zobrazit uložené outfity",
    dressup = "Obléknout se",
    rename = "Přejmenovat",
    renameoutfit = "Přejmenovat outfit",
    renameoutfitname = "Nový název outfitu",
    delete = "Smazat",
    title = "Taška s oblečením",
    placeditem = "Úspěšně jsi položil tašku s oblečením.",
}


]]