fx_version 'cerulean'
game 'gta5'
author 'OS Mapping'

files {
    'swmonitor01.ytyp',
    'swmonitor02.ytyp',
    'swmonitor03.ytyp',
    'swmonitor04.ytyp',
    'swmonitor05.ytyp',
    'swmonitor06.ytyp',
    'swmonitor07.ytyp',
    'swmonitor08.ytyp',
    'swmonitor09.ytyp',
    'swmonitor10.ytyp',
    'swmonitor11.ytyp',
    'swmonitor12.ytyp',
    'r_stryker.ytyp',
    'r_stryker_1.ydr',
    'r_stryker_2.ydr',
    'r_stryker_de_1.ydr',
    'r_stryker_de_2.ydr',
    'r_stryker_shell_1.ydr',
    'r4houselrg1.ytyp',
    'r4housemed1.ytyp',
    'r4housemed2.ytyp',
    'r4housemed3.ytyp',
    'r4housemed4.ytyp',
    'r4housesm1.ytyp',
    'swbarrier01.ytyp',
    'swbarrier02.ytyp',
    'swbarriertall.ytyp',
    'charliewatchtower1.ytyp',
    'r_mraposhkosh.ytyp',
    'r_mraposhkosh_1.ytd',
    'Cayo_Village.ymap',
    'h4_islandx_terrain_05.ymap',
    'h4_islandx_terrain_05_lod.ymap',
    'h4_islandx_terrain_props_05_a.ymap',
    'h4_islandx_terrain_props_05_a_lod.ymap',
    'h4_islandx_terrain_props_05_b.ymap',
    'h4_islandx_terrain_props_05_b_lod.ymap',
    'h4_islandx_terrain_props_05_c.ymap',
    'h4_islandx_terrain_props_05_d.ymap',
    'h4_islandx_terrain_props_05_d_lod.ymap',
    'h4_islandx_terrain_props_05_e.ymap',
    'h4_islandx_terrain_props_05_e_lod.ymap',
    'h4_islandx_terrain_props_05_f.ymap',
    'cs_ground_beton.ytyp'
}

-- Datenstreams
data_file 'STREAMING_FILE_TABLE' {
    'swmonitor01.ydr',
    'swmonitor02.ydr',
    'swmonitor03.ydr',
    'swmonitor04.ydr',
    'swmonitor05.ydr',
    'swmonitor06.ydr',
    'swmonitor07.ydr',
    'swmonitor08.ydr',
    'swmonitor09.ydr',
    'swmonitor10.ydr',
    'swmonitor11.ydr',
    'swmonitor12.ydr',
    'r4houselrg1.ydr',
    'r4housemed1.ydr',
    'r4housemed2.ydr',
    'r4housemed3.ydr',
    'r4housemed4.ydr',
    'r4housesm1.ydr',
    'swbarrier01.ydr',
    'swbarrier02.ydr',
    'swbarriertall.ydr',
    'charliewatchtower1.ydr',
    'r_mraposhkosh_1.ydr',
    'r_mraposhkosh_2.ydr',
    'r_mraposhkosh_3.ydr',
    'r_mraposhkosh_4.ydr',
    'r_mraposhkosh_dmg_1.ydr',
    'r_mraposhkosh_tire_1.ydr',
    'r_mraposhkosh_tire_2.ydr',
    'r_mraposhkosh_turret_1.ydr',
    'r_mraposhkosh_turret_2.ydr',
    'cs_ground_beton.ydr'
}

data_file 'DLC_ITYP_REQUEST' {
    'swmonitor01.ytyp',
    'swmonitor02.ytyp',
    'swmonitor03.ytyp',
    'swmonitor04.ytyp',
    'swmonitor05.ytyp',
    'swmonitor06.ytyp',
    'swmonitor07.ytyp',
    'swmonitor08.ytyp',
    'swmonitor09.ytyp',
    'swmonitor10.ytyp',
    'swmonitor11.ytyp',
    'swmonitor12.ytyp',
    'r_stryker.ytyp',
    'r4houselrg1.ytyp',
    'r4housemed1.ytyp',
    'r4housemed2.ytyp',
    'r4housemed3.ytyp',
    'r4housemed4.ytyp',
    'r4housesm1.ytyp',
    'swbarrier01.ytyp',
    'swbarrier02.ytyp',
    'swbarriertall.ytyp',
    'charliewatchtower1.ytyp',
    'r_mraposhkosh.ytyp',
    'cs_ground_beton.ytyp'
}

data_file 'SCENARIO_INFO_FILE' 'Cayo_Village.ymap'